# Generated by Django 4.0.3 on 2022-04-07 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(max_length=150)),
                ('position', models.CharField(choices=[('CEO', 'CEO'), ('MMM', 'Middle manager manager'), ('MM', 'Middle manager'), ('SM', 'Subordinate manager'), ('SW', 'Simple worker')], default='SW', max_length=200)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('hiring_date', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_salary', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'permissions': [('kek', 'kek')],
            },
        ),
        migrations.CreateModel(
            name='WorkerRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='head_of_workers', to='factory_management.worker')),
                ('secondary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_workers', to='factory_management.worker')),
            ],
        ),
    ]
